module.exports.configLDAP = require("./src/ldap")
module.exports.configServer = require("./src/server")
module.exports.configApp = require("./src/app")
module.exports.configSession = require("./src/session")
module.exports.configDatabase = require("./src/database")
