export { userController } from "./user"
export { authController } from "./auth"
export { logController } from "./log"
export { mailController } from "./mail"
export { uploadController } from "./upload"
//export { gdriveSetup } from "./gdrive"
//export { uploadController } from "./uploadfile"
