module.exports.configLDAP = require("./src/ldap")
module.exports.configServer = require("./src/server")
module.exports.configApp = require("./src/app")
module.exports.configTheme = require("./src/theme")
module.exports.configRoute = require("./src/route")
